version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd warped-mirrors/landing-page
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - cd warped-mirrors/landing-page
      - npm run build
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: warped-mirrors/landing-page/dist
cache:
  paths:
    - 'warped-mirrors/landing-page/node_modules/**/*'
